project:
  type: book
  output-dir: docs
  
execute:
  freeze: false

book:
  title: "ClassifyR PlayBook"
  author: "Dario Strbenac, Jasmine Gu, Jean Yang and Ellis Patrick"
  chapters:
    - index.qmd
    - Procedure1.qmd
    - Procedure2.qmd
    - Procedure3.qmd
  navbar:
    logo: images/USydLogo.svg
  sidebar:
    collapse-level: 2 # Make sections (level 2) collapsible  
    search: true


bibliography: references.bib

format:
  html:
    theme: [cosmo, styles.scss]
    css: styles.css


editor: visual

